{
  "hash": "de6b95c5dbdba107b4cf6d12ba1f16f7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Basic Statistics\"\nsubtitle: \"Concepts, Formulas, and Applications in R\"\nauthor: \"Pawan\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n    code-fold: false\n    highlight-style: github\n  pdf:\n    toc: true\n    number-sections: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n# Introduction\n\n**Basic statistics** is the foundation of all data analysis. It provides tools to summarize, describe, and understand data before performing any advanced modelling. It answers the most fundamental question: *What does the data look like?*\n\n---\n\n# Key Concepts and Definitions\n\n## 1. Population vs Sample\n\n- **Population**: The complete set of all items of interest (e.g., all students in India).\n- **Sample**: A subset of the population selected for study (e.g., 500 students from Delhi).\n\nWe use **sample statistics** to estimate **population parameters**.\n\n| Measure | Population Symbol | Sample Symbol |\n|---------|------------------|---------------|\n| Mean | μ (mu) | x̄ |\n| Standard Deviation | σ (sigma) | s |\n| Size | N | n |\n\n---\n\n## 2. Measures of Central Tendency\n\nThese describe the **centre** of the data.\n\n### Mean (Arithmetic Average)\n\n$$\\bar{x} = \\frac{\\sum_{i=1}^{n} x_i}{n}$$\n\n### Median\n\nThe **middle value** when data is sorted. For $n$ observations:\n\n- If $n$ is odd: Median = $\\left(\\frac{n+1}{2}\\right)$th value\n- If $n$ is even: Median = average of $\\left(\\frac{n}{2}\\right)$th and $\\left(\\frac{n}{2}+1\\right)$th values\n\n### Mode\n\nThe value that **occurs most frequently** in the dataset.\n\n---\n\n## 3. Measures of Dispersion\n\nThese describe how **spread out** the data is.\n\n### Variance\n\n$$s^2 = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})^2}{n-1}$$\n\n### Standard Deviation\n\n$$s = \\sqrt{\\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})^2}{n-1}}$$\n\n### Range\n\n$$\\text{Range} = x_{\\max} - x_{\\min}$$\n\n### Interquartile Range (IQR)\n\n$$\\text{IQR} = Q_3 - Q_1$$\n\nwhere $Q_1$ = 25th percentile and $Q_3$ = 75th percentile.\n\n---\n\n## 4. Measures of Shape\n\n### Skewness\n\nMeasures **asymmetry** of the distribution.\n\n$$\\text{Skewness} = \\frac{1}{n} \\sum_{i=1}^{n} \\left(\\frac{x_i - \\bar{x}}{s}\\right)^3$$\n\n- Skewness = 0 → Symmetric\n- Skewness > 0 → Right-skewed (tail on the right)\n- Skewness < 0 → Left-skewed (tail on the left)\n\n### Kurtosis\n\nMeasures **peakedness** of the distribution.\n\n$$\\text{Kurtosis} = \\frac{1}{n} \\sum_{i=1}^{n} \\left(\\frac{x_i - \\bar{x}}{s}\\right)^4$$\n\n---\n\n# When and Where to Use Basic Statistics\n\n| Situation | Tool |\n|-----------|------|\n| Summarising exam scores | Mean, Median, SD |\n| Comparing income distributions | Median, IQR (robust to outliers) |\n| Understanding data shape | Skewness, Kurtosis |\n| Checking data spread | Variance, Range |\n| Exploratory Data Analysis (EDA) | All of the above |\n\n**Real-world examples:**\n- A hospital computes the **mean** age of patients to plan resources.\n- An economist uses the **median** income (not mean) because income data is right-skewed.\n- A teacher computes **standard deviation** of marks to judge class variability.\n\n---\n\n# Implementation in R\n\n## Loading and Exploring Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use the built-in 'mtcars' dataset\ndata(mtcars)\n\n# First look at the data\nhead(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   mpg cyl disp  hp drat    wt  qsec vs am gear carb\nMazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4\nMazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4\nDatsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1\nHornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1\nHornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2\nValiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t32 obs. of  11 variables:\n $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...\n $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...\n $ disp: num  160 160 108 258 360 ...\n $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...\n $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...\n $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...\n $ qsec: num  16.5 17 18.6 19.4 17 ...\n $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...\n $ am  : num  1 1 1 0 0 0 0 0 0 0 ...\n $ gear: num  4 4 4 3 3 3 3 4 4 4 ...\n $ carb: num  4 4 1 1 2 1 4 2 2 4 ...\n```\n\n\n:::\n:::\n\n\n## Measures of Central Tendency\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Focus on miles per gallon (mpg)\nx <- mtcars$mpg\n\ncat(\"Mean    :\", mean(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean    : 20.09062 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median  :\", median(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian  : 19.2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mode    :\", as.numeric(names(sort(table(x), decreasing = TRUE)[1])), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMode    : 10.4 \n```\n\n\n:::\n:::\n\n\n## Measures of Dispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Variance:\", var(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariance: 36.3241 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Std Dev :\", sd(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStd Dev : 6.026948 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Range   :\", range(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRange   : 10.4 33.9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IQR     :\", IQR(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIQR     : 7.375 \n```\n\n\n:::\n:::\n\n\n## Quantiles and Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Five-number summary + mean\nsummary(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  10.40   15.43   19.20   20.09   22.80   33.90 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Custom quantiles\nquantile(x, probs = c(0.25, 0.50, 0.75, 0.90))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   25%    50%    75%    90% \n15.425 19.200 22.800 30.090 \n```\n\n\n:::\n:::\n\n\n## Skewness and Kurtosis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install e1071 if not available: install.packages(\"e1071\")\nlibrary(e1071)\n\ncat(\"Skewness:\", skewness(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSkewness: 0.610655 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Kurtosis:\", kurtosis(x), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKurtosis: -0.372766 \n```\n\n\n:::\n:::\n\n\n## Full Descriptive Statistics Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A clean descriptive statistics summary\ndesc_stats <- data.frame(\n  Statistic = c(\"N\", \"Mean\", \"Median\", \"SD\", \"Variance\",\n                \"Min\", \"Max\", \"Range\", \"IQR\", \"Skewness\", \"Kurtosis\"),\n  Value = round(c(\n    length(x), mean(x), median(x), sd(x), var(x),\n    min(x), max(x), diff(range(x)), IQR(x),\n    skewness(x), kurtosis(x)\n  ), 3)\n)\n\nprint(desc_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Statistic  Value\n1          N 32.000\n2       Mean 20.091\n3     Median 19.200\n4         SD  6.027\n5   Variance 36.324\n6        Min 10.400\n7        Max 33.900\n8      Range 23.500\n9        IQR  7.375\n10  Skewness  0.611\n11  Kurtosis -0.373\n```\n\n\n:::\n:::\n\n\n## Visualisation\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3))\n\n# Histogram\nhist(x,\n     main = \"Distribution of MPG\",\n     xlab = \"Miles Per Gallon\",\n     col = \"steelblue\", border = \"white\",\n     breaks = 10)\nabline(v = mean(x), col = \"red\", lwd = 2, lty = 2)\nabline(v = median(x), col = \"darkgreen\", lwd = 2, lty = 2)\nlegend(\"topright\", legend = c(\"Mean\", \"Median\"),\n       col = c(\"red\", \"darkgreen\"), lty = 2, lwd = 2)\n\n# Boxplot\nboxplot(x,\n        main = \"Boxplot of MPG\",\n        ylab = \"Miles Per Gallon\",\n        col = \"lightblue\", border = \"navy\")\n\n# QQ Plot (normality check)\nqqnorm(x, main = \"Normal Q-Q Plot\")\nqqline(x, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](01_basic_statistics_files/figure-html/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n---\n\n# Interpretation\n\nLooking at the MPG data from `mtcars`:\n\n- The **mean MPG** (~20.09) is slightly higher than the **median** (~19.2), suggesting a mild right skew.\n- The **standard deviation** (~6.03) tells us most cars fall within ±6 MPG of the mean.\n- The **IQR** spans from ~15.4 to ~22.8 MPG, covering the middle 50% of cars.\n- The **Q-Q plot** helps assess if the data follows a normal distribution.\n\n---\n\n# Summary\n\n> Basic statistics transforms raw numbers into meaningful insights. Always start any data analysis by computing and visualising these descriptive measures — they guide every decision that follows.\n\n| What | Formula | R Function |\n|------|---------|-----------|\n| Mean | $\\bar{x} = \\frac{\\sum x_i}{n}$ | `mean()` |\n| Median | Middle value | `median()` |\n| Variance | $s^2 = \\frac{\\sum(x_i - \\bar{x})^2}{n-1}$ | `var()` |\n| Std Dev | $s = \\sqrt{s^2}$ | `sd()` |\n| IQR | $Q_3 - Q_1$ | `IQR()` |\n| Summary | All at once | `summary()` |\n",
    "supporting": [
      "01_basic_statistics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}